- src/app/page.tsx
> TOP のデザイン修正

- src/app/globals.css
> tailwid css の修正

- src/app/page.tsx
ボタンので候補日を見る画面に遷移できるようになった
TOPにボタンを追加した
2
> TOPにボタンを追加

- components.json
- package-lock.json
- package.json
- src/app/candidate/page.tsx
- src/app/globals.css
- src/components/ui/card.tsx
- src/components/ui/input.tsx
- src/components/ui/table.tsx
- src/lib/utils.ts
- tailwind.config.ts
予定調整相手の空き時間が見られるようになりました。
- ダミーデータを入れた状態で、予定調整空いての空き時間を表示するページを作成しました。
- V0を利用してコードを作成しました。（https://v0.dev/chat/I9Ii6CfPw6g?b=b_wcYsUur7stI&p=0）
- chadcn / ui を導入しました。
task 3
> 予定調整ページの画面を作成しました。 task3

- package-lock.json
- package.json
- src/app/adjust/page.tsx
- src/app/page.tsx
- src/components/ui/button.tsx
- src/components/ui/checkbox.tsx
- src/components/ui/label.tsx
0 コストで日程調整をする画面を作成しました。
データはすべてダミー
Google への予定追加は予定追加 URL で実装
> 0コスト日程調整の検証

- src/app/page.tsx
トップ画面からこのアプリが何をするものか分かる
説明追加
5
> added description

- src/app/adjust/page.tsx
- src/app/retry/[id]/page.tsx
- src/lib/utils.ts
一応リトライできる
random dateでリトライ
- [ -] 自分で碼書の振り返りをしました
> random retry

- package-lock.json
- package.json
- src/app/adjust/page.tsx
- カレンダーの詳細から日程調整のリトライを試みれるようになりました。
- 初回日程調整結果のイメージが掴みやすくなりました。
- リトライURLをカレンダー詳細に追加しました。
- 日程調整結果の予定の時間幅が存在するようにしました。
> リトライURLの追加、日程調整結果のイメージの修正

- next-auth.d.ts
- package-lock.json
- package.json
- src/app/mycalendar/page.tsx
- src/lib/auth.ts
- src/lib/googleApi.ts
- src/lib/googleCalendar.ts
- src/lib/prisma.ts
- src/logic/calendar.ts
- ログイン時に Google Calendar へのアクセス権限を本アプリに付与できるようになりました。
- ログインしたユーザの Google Calendar の情報を取得できるようになりました。
デバック用に `/mycalendar` にアクセスすると取得した予定の情報が表示されます。
> Google Calendar からイベントを取得する

- .gitignore
- public/イラスト5_2 2.svg:Zone.Identifier
> 🐛 Remove garbage file and ignore it

- .gitignore
- public/イラスト5_2 2.svg:Zone.Identifier
- src/app/adjust/page.tsx
- src/app/mycalendar/page.tsx
- src/lib/getEvents.ts
- src/lib/scheduling.ts
- src/lib/utils.ts
ログインしていればGCalの予定から空き時間を探して予定を入れる
> 主催者の空き時間に予定時刻を設定

- .gitignore
- package.json
- src/lib/scheduling.spec.ts
日程調整アルゴリズムのテストを書いた。
#28, #29 に関連
> ✅ Add unit test for scheduling algorithm

- src/app/adjust/client.tsx
調整が始まったこと、終わったことが視覚的に確認しやすくなった。
（本当はスピナーや進捗バーを表示したい）
調整アルゴリズムが走っている間にボタンを無効化し、完了後に復活するようにした。
None
> 🚸 Disable button while scheduling to improve UX

- src/app/adjust/page.tsx
-予定確保時間をプルダウンメニューから選択できる（180分まで、30分刻み）
-予定確保時間選択できるプルダウンメニューのUIを作成した。
-機能的な接続はまだできていない。
-まだエラーは出ているので、マージはしなくてよい。
#25
> 確保時間選択UIを作ろうとしたがエラーが出ている

- src/app/adjust/client.tsx
- src/lib/scheduling.ts
- src/lib/utils.ts
- 除外時間を設定することができる状態に近づきました。
- 除外時間を設定するフォームの処理部分を作成しました。
- フォームから受け取った除外時間をScheduling()に渡しています
- 渡された除外時間を予定としてeventsOfUsers: Period[][]に加工する処理はまだ書いていません
> Scheduling exclusion

- src/app/adjust/client.tsx
- src/lib/addEvent.ts
- src/lib/googleCalendar.ts
- src/logic/calendar.ts
※途中まで作ったので、他の方に続きは託します（細川）
調整ボタンを押すと、自動で Google Calendar に予定が追加されるようになりました。
- Google Calendar に予定を追加する API を呼びました。
- 既存の Calendar に書き込む権限があると、バグってユーザの予定を破壊するリスク（or 疑いをかけられる）ので新規にカレンダーを追加するようにしました。
> [WIP] Google Calendar への追加

- src/app/adjust/WeekView.tsx
- src/app/adjust/candidate.tsx
- src/app/adjust/draft/EventModal.tsx
- src/app/adjust/draft/WeekView.tsx
- src/app/adjust/draft/page.tsx
- src/app/adjust/draft/types.ts
- src/app/adjust/draft/utils.ts
カレンダー形式で日時の候補が選べるようになった。
v0 の助けを借りて adjust/WeekView を実装。v0の出力ファイルは adjust/draft以下にとりあえず置いた。
> Calendar candidate selection UI

- src/app/adjust/WeekView.tsx
- src/app/adjust/client.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/components/UserWidget.tsx
/adjust の max-width を md から 4xl にしてカレンダーが見切れないようにした
> changed max width of adjust page, set bg-white for header

- src/app/adjust/candidate.tsx
正常終了時も異常終了時も統一されたインタフェースで応答を得られるようになりました。
alert() を使ったエラー表示を react-toastify へ変更。
#58 (fix #58)
> 💄 エラー表示をトーストに統一

- src/app/adjust/WeekView.tsx
- src/app/adjust/candidate.tsx
- src/app/adjust/client.tsx
- src/app/adjust/page.tsx
- src/components/ImportFile.tsx
- src/components/ImportFileButton.tsx
- src/components/ui/tooltip.tsx
- src/lib/course.ts
- src/lib/utils.ts
- src/third-party/twinte-parser-type.ts
- src/third-party/twinte-parser.ts
コメントを追加しました．
パッと見て理解しやすいと思えるように，一部でプログラム的にほぼ等価な書き換えをしました．
いかがでしょう．
> ♻️ 可読性向上のための提案

- src/lib/auth.ts
- src/lib/getEvents.ts
- src/lib/googleApi.ts
- 日程調整時に出るエラーを修正しました。
- 他人の予定を取得するときの invalid credentials エラーを修正
- 現状はセッション取得時にしか access token を更新しないが、それだと他人の予定を取得する時に更新されないので、他人の時間を取得するときにも更新するように
> 日程調整時に出るエラーを修正
